//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notation
    {
        public Notation()
        {
            this.Teacher = new HashSet<Teacher>();
        }
    
        public int Id { get; set; }
        public string ListValue { get; set; }
        public Nullable<int> SizeList { get; set; }
        public Nullable<int> FinalNotation { get; set; }
    
        public virtual ICollection<Teacher> Teacher { get; set; }
    }
}
