//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Firstname { get; set; }
        public string PromotionValidation { get; set; }
        public string PromotionCurrent { get; set; }
        public string Email { get; set; }
        public int IdCampus { get; set; }
        public int IdCampusWould { get; set; }
        public Nullable<int> IdCampusTeach { get; set; }
        public string IdCoursesWould { get; set; }
        public string IdCoursesTeach { get; set; }
        public Nullable<int> IdCertification { get; set; }
        public Nullable<int> IdNotation { get; set; }
        public string Comments { get; set; }
    
        public virtual Campus Campus { get; set; }
        public virtual Campus Campus1 { get; set; }
        public virtual Campus Campus2 { get; set; }
        public virtual Certification Certification { get; set; }
        public virtual Courses Courses { get; set; }
        public virtual Courses Courses1 { get; set; }
        public virtual Notation Notation { get; set; }
    }
}
