//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _164253
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certification
    {
        public Certification()
        {
            this.Teacher = new HashSet<Teacher>();
        }
    
        public int Id { get; set; }
        public string NameCertification { get; set; }
        public string Grade { get; set; }
    
        public virtual ICollection<Teacher> Teacher { get; set; }
    }
}
